runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /img
  static_dir: img

- url: /paintingimages
  static_dir: paintingimages

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /admin.*
  script: mchopa_admin.app
  login: admin

- url: /.*
  script: mchopa_site.app
